### ISSUE TITLE
Can't pull docker images from private repositories

### ISSUE THREAD

**Issue by marsdalesa** [Adhara-Tech/itrunner#20]
IT runner is unable to pull docker images from private repositories requiring credentials.

We'll need to be able to read docker config.json files as well as take in arguments.

**Comment by rafa-adhara** [comment]
`itrunner` now supports environment variables to be provided to configuration and dependency files.

With this addition you can use `dockerauth` to pull private docker images.

![Screenshot from 2023-07-06 12-28-22](https://github.com/Adhara-Tech/itrunner/assets/49152351/16aff6c1-f276-47e5-9d01-c43dcdf05b91)
